[package]
name = "tree-grepper"
version = "0.1.0"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
thiserror = "1.0"
tree-sitter = "0.17"
walkdir = "2.3"

[build-dependencies]
cc = { version = "*", features = [ "parallel" ] }
