[package]
name = "tree-grepper"
version = "2.0.3"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.43"
bump_alloc = "0.1.0"
clap = "=3.0.0-beta.2"
ignore = "0.4.18"
itertools = "0.10.1"
rayon = "1.5.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
tree-sitter = "0.19.5"

[dev-dependencies]
insta = "1.7.2"

[build-dependencies]
cc = { version = "1.0.70", features = [ "parallel" ] }
