[package]
name = "tree-grepper"
version = "2.3.0"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.53"
bump_alloc = "0.1.0"
clap = { version = "3.0.14", features = [ "std", "color", "suggestions", "cargo" ] }
crossbeam = "0.8.1"
ignore = "0.4.18"
itertools = "0.10.3"
rayon = "1.5.1"
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0.79"
tree-sitter = "0.20.4"

[dev-dependencies]
insta = "1.12.0"

[build-dependencies]
cc = { version = "1.0.73", features = [ "parallel" ] }
