[package]
name = "tree-grepper"
version = "2.5.0-pre"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.79"
bump_alloc = "0.1.0"
clap = { version = "4.4.18", features = [ "std", "color", "suggestions", "cargo" ] }
crossbeam = "0.8.4"
ignore = "0.4.22"
itertools = "0.12.1"
rayon = "1.8.1"
serde = { version = "1.0.196", features = [ "derive" ] }
serde_json = "1.0.113"
strum = "0.25"
strum_macros = "0.25"
tree-sitter = "0.20.10"

[build-dependencies]
cc = { version = "1.0.84", features = [ "parallel" ] }

[dev-dependencies]
trycmd = "0.14.20"
