[package]
name = "tree-grepper"
version = "2.5.0-pre"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.81"
bump_alloc = "0.1.0"
clap = { version = "4.5.3", features = [ "std", "color", "suggestions", "cargo" ] }
crossbeam = "0.8.4"
ignore = "0.4.22"
itertools = "0.12.1"
rayon = "1.9.0"
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
strum = "0.26.2"
strum_macros = "0.26.2"
tree-sitter = "0.22.2"

[build-dependencies]
cc = { version = "1.0.90", features = [ "parallel" ] }

[dev-dependencies]
trycmd = "0.15.0"
