[package]
name = "tree-grepper"
version = "2.5.0-pre"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.66"
bump_alloc = "0.1.0"
clap = { version = "4.0.29", features = [ "std", "color", "suggestions", "cargo" ] }
crossbeam = "0.8.2"
ignore = "0.4.18"
itertools = "0.10.5"
rayon = "1.6.1"
serde = { version = "1.0.150", features = [ "derive" ] }
serde_json = "1.0.89"
strum = "0.24"
strum_macros = "0.24"
tree-sitter = "0.20.9"

[build-dependencies]
cc = { version = "1.0.77", features = [ "parallel" ] }
