[package]
name = "tree-grepper"
version = "2.0.0"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"

[build-dependencies]
cc = { version = "*", features = [ "parallel" ] }
