[package]
name = "tree-grepper"
version = "2.5.0-pre"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.71"
bump_alloc = "0.1.0"
clap = { version = "4.2.7", features = [ "std", "color", "suggestions", "cargo" ] }
crossbeam = "0.8.2"
ignore = "0.4.20"
itertools = "0.10.5"
rayon = "1.7.0"
serde = { version = "1.0.160", features = [ "derive" ] }
serde_json = "1.0.96"
strum = "0.24"
strum_macros = "0.24"
tree-sitter = "0.20.10"

[build-dependencies]
cc = { version = "1.0.79", features = [ "parallel" ] }

[dev-dependencies]
trycmd = "0.14.16"
