[package]
name = "tree-grepper"
version = "2.2.0"
authors = ["Brian Hicks <brian@brianthicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bump_alloc = "0.1.0"
clap = { version = "3.0.1", features = [ "std", "color", "suggestions", "cargo" ] }
crossbeam = "0.8.1"
ignore = "0.4.18"
itertools = "0.10.3"
rayon = "1.5.1"
serde = { version = "1.0.133", features = [ "derive" ] }
serde_json = "1.0.74"
tree-sitter = "0.20.2"

[dev-dependencies]
insta = "1.9.0"

[build-dependencies]
cc = { version = "1.0.72", features = [ "parallel" ] }
