name: CI

on:
  pull_request:
  push:

jobs:
  build-and-test:
    name: build and test
    strategy:
      matrix:
        # note: we're using ubuntu-latest as a stand-in for all Linux
        # distributions. If we find we need more, we should do Docker stuff.
        os: [ubuntu-latest, macos-11]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: tree-grepper
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-build

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: tree-grepper
          skipPush: true

      - run: nix-shell --pure --run 'rustfmt --check $(find . -name "*.rs" -not -ipath "*vendor*" -not -ipath "*target*")'
