name: CI

on:
  pull_request:
  push:

jobs:
  build-and-test:
    name: build and test
    strategy:
      matrix:
        # note: we're using ubuntu-latest as a stand-in for all Linux
        # distributions. If we find we need more, we should do Docker stuff.
        #
        # We're testing on two versions of macOS because those are the ones
        # that my coworkers use, and I've added tree-grepper to our main repo's
        # dependencies. Once most everyone's on Big Sur (11), I'll probably
        # drop Catalina (10.15) to save on build time and resources.
        os: [ubuntu-latest, macos-10.15, macos-11]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: tree-grepper
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-build

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: tree-grepper
          skipPush: true

      - run: nix-shell --pure --run 'cargo clippy'

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: tree-grepper
          skipPush: true

      - run: nix-shell --pure --run 'rustfmt --check $(find . -name "*.rs" -not -ipath "*vendor*" -not -ipath "*target*")'
